### ISSUE TITLE
How to update context during run 

### ISSUE THREAD

**Issue by imcvampire** [yesmeck/camas#2]
Hi,

How can I update context dynamically (during runtime)? 

Thank you!

**Comment by yesmeck** [comment]
In general, context is derived from the  state of your application, when the state updates, context will be updated eventually.

You can refer to this [live demo](https://codesandbox.io/s/camas-demo-17pjy) to see how I update the role of user at runtime.

**Comment by imcvampire** [comment]
Thank you!
